services:
  YounitedpayClasslib\Extensions\ProcessLogger\ProcessLoggerHandler:
    class: 'YounitedpayClasslib\Extensions\ProcessLogger\ProcessLoggerHandler'

  YounitedpayAddon\Service\ConfigService:
    class: 'YounitedpayAddon\Service\ConfigService'
    arguments:
      - '@YounitedpayClasslib\Extensions\ProcessLogger\ProcessLoggerHandler'